export const typography = {
    headlineOneFontFamily: "Roboto",
    headlineOneFontSize: 96,
    headlineOneLineHeight: 96,
    headlineOneFontWeight: 300,
    headlineOneLetterSpacing: -1.5,
    headlineOneTextDecoration: "inherit",
    headlineOneTextTransform: "inherit",

    headlineTwoFontFamily: "Roboto",
    headlineTwoFontSize: 60,
    headlineTwoLineHeight: 60,
    headlineTwoFontWeight: 300,
    headlineTwoLetterSpacing: -0.5,
    headlineTwoTextDecoration: "inherit",
    headlineTwoTextTransform: "inherit",

    headlineThreeFontFamily: "Roboto",
    headlineThreeFontSize: 48,
    headlineThreeLineHeight: 50,
    headlineThreeFontWeight: 400,
    headlineThreeLetterSpacing: 1,
    headlineThreeTextDecoration: "inherit",
    headlineThreeTextTransform: "inherit",

    headlineFourFontFamily: "Roboto",
    headlineFourFontSize: 34,
    headlineFourLineHeight: 40,
    headlineFourFontWeight: 400,
    headlineFourLetterSpacing: 0.25,
    headlineFourTextDecoration: "inherit",
    headlineFourTextTransform: "inherit",

    headlineFiveFontFamily: "Roboto",
    headlineFiveFontSize: 24,
    headlineFiveLineHeight: 32,
    headlineFiveFontWeight: 400,
    headlineFiveLetterSpacing: 1,
    headlineFiveTextDecoration: "inherit",
    headlineFiveTextTransform: "inherit",

    headlineSixFontFamily: "Roboto",
    headlineSixFontSize: 20,
    headlineSixLineHeight: 32,
    headlineSixFontWeight: 500,
    headlineSixLetterSpacing: 0.25,
    headlineSixTextDecoration: "inherit",
    headlineSixTextTransform: "inherit",

    subtitleOneFontFamily: "Roboto",
    subtitleOneFontSize: 16,
    subtitleOneLineHeight: 28,
    subtitleOneFontWeight: 400,
    subtitleOneLetterSpacing: 0.15,
    subtitleOneTextDecoration: "inherit",
    subtitleOneTextTransform: "inherit",

    subtitleTwoFontFamily: "Roboto",
    subtitleTwoFontSize: 14,
    subtitleTwoLineHeight: 22,
    subtitleTwoFontWeight: 500,
    subtitleTwoLetterSpacing: 0.1,
    subtitleTwoTextDecoration: "inherit",
    subtitleTwoTextTransform: "inherit",

    bodyOneFontFamily: "Roboto",
    bodyOneFontSize: 16,
    bodyOneLineHeight: 24,
    bodyOneFontWeight: 400,
    bodyOneLetterSpacing: 0.5,
    bodyOneTextDecoration: "inherit",
    bodyOneTextTransform: "inherit",

    bodyTwoFontFamily: "Roboto",
    bodyTwoFontSize: 14,
    bodyTwoLineHeight: 20,
    bodyTwoFontWeight: 400,
    bodyTwoLetterSpacing: 0.25,
    bodyTwoTextDecoration: "inherit",
    bodyTwoTextTransform: "inherit",

    captionFontFamily: "Roboto",
    captionFontSize: 12,
    captionLineHeight: 20,
    captionFontWeight: 400,
    captionLetterSpacing: 0.4,
    captionTextDecoration: "inherit",
    captionTextTransform: "inherit",

    buttonFontFamily: "Roboto",
    buttonFontSize: 14,
    buttonLineHeight: 36,
    buttonFontWeight: 600,
    buttonLetterSpacing: 1.25,
    buttonTextDecoration: "inherit",
    buttonTextTransform: "inherit",

    overlineFontFamily: "Roboto",
    overlineFontSize: 12,
    overlineLineHeight: 32,
    overlineFontWeight: 500,
    overlineLetterSpacing: 2,
    overlineTextDecoration: "inherit",
    overlineTextTransform: "inherit",
};
