const primarySansSerifFontFamily = '"proxima-nova", "Helvetica Neue", Helvetica, Arial, sans-serif';

export const typography = {
    headline1FontFamily: primarySansSerifFontFamily,
    headline1FontSize: 96,
    headline1LineHeight: 96,
    headline1FontWeight: 300,
    headline1LetterSpacing: -1.5,
    headline1TextDecoration: undefined,
    headline1TextTransform: undefined,

    headline2FontFamily: primarySansSerifFontFamily,
    headline2FontSize: 60,
    headline2LineHeight: 60,
    headline2FontWeight: 300,
    headline2LetterSpacing: -0.5,
    headline2TextDecoration: undefined,
    headline2TextTransform: undefined,

    headline3FontFamily: primarySansSerifFontFamily,
    headline3FontSize: 48,
    headline3LineHeight: 50,
    headline3FontWeight: 400,
    headline3LetterSpacing: 1,
    headline3TextDecoration: undefined,
    headline3TextTransform: undefined,

    headline4FontFamily: primarySansSerifFontFamily,
    headline4FontSize: 34,
    headline4LineHeight: 40,
    headline4FontWeight: 400,
    headline4LetterSpacing: 0.25,
    headline4TextDecoration: undefined,
    headline4TextTransform: undefined,

    headline5FontFamily: primarySansSerifFontFamily,
    headline5FontSize: 24,
    headline5LineHeight: 32,
    headline5FontWeight: 400,
    headline5LetterSpacing: 1,
    headline5TextDecoration: undefined,
    headline5TextTransform: undefined,

    headline6FontFamily: primarySansSerifFontFamily,
    headline6FontSize: 20,
    headline6LineHeight: 32,
    headline6FontWeight: 500,
    headline6LetterSpacing: 0.25,
    headline6TextDecoration: undefined,
    headline6TextTransform: undefined,

    subtitle1FontFamily: primarySansSerifFontFamily,
    subtitle1FontSize: 16,
    subtitle1LineHeight: 28,
    subtitle1FontWeight: 400,
    subtitle1LetterSpacing: 0.15,
    subtitle1TextDecoration: undefined,
    subtitle1TextTransform: undefined,

    subtitle2FontFamily: primarySansSerifFontFamily,
    subtitle2FontSize: 14,
    subtitle2LineHeight: 22,
    subtitle2FontWeight: 500,
    subtitle2LetterSpacing: 0.1,
    subtitle2TextDecoration: undefined,
    subtitle2TextTransform: undefined,

    body1FontFamily: primarySansSerifFontFamily,
    body1FontSize: 16,
    body1LineHeight: 24,
    body1FontWeight: 400,
    body1LetterSpacing: 0.5,
    body1TextDecoration: undefined,
    body1TextTransform: undefined,

    body3FontFamily: primarySansSerifFontFamily,
    body3FontSize: 14,
    body3LineHeight: 20,
    body3FontWeight: 400,
    body3LetterSpacing: 0.25,
    body3TextDecoration: undefined,
    body3TextTransform: undefined,

    captionFontFamily: primarySansSerifFontFamily,
    captionFontSize: 12,
    captionLineHeight: 20,
    captionFontWeight: 400,
    captionLetterSpacing: 0.4,
    captionTextDecoration: undefined,
    captionTextTransform: undefined,

    buttonFontFamily: primarySansSerifFontFamily,
    buttonFontSize: 14,
    buttonLineHeight: 36,
    buttonFontWeight: 500,
    buttonLetterSpacing: 1.25,
    buttonTextDecoration: undefined,
    buttonTextTransform: undefined,

    overlineFontFamily: primarySansSerifFontFamily,
    overlineFontSize: 12,
    overlineLineHeight: 32,
    overlineFontWeight: 500,
    overlineLetterSpacing: 2,
    overlineTextDecoration: undefined,
    overlineTextTransform: undefined,
};
